### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by liushifu12138** [ArthasMil/AACVP-MVSNet#10]
Traceback (most recent call last):
  File "train_AACVPMVSNet.py", line 95, in <module>
    model = nn.DataParallel(model, device_ids=device_ids, output_device=device_ids[0])
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 142, in __init__
    _check_balance(self.device_ids)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 23, in _check_balance
    dev_props = _get_devices_properties(device_ids)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/_utils.py", line 458, in _get_devices_properties
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/_utils.py", line 458, in <listcomp>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/_utils.py", line 441, in _get_device_attr
    return get_member(torch.cuda)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/_utils.py", line 458, in <lambda>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/cuda/__init__.py", line 299, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id

**Comment by ArthasMil** [comment]
I think this problem arises when the gpu ids are not configured correctly. You may want to check [this line](https://github.com/ArthasMil/AACVP-MVSNet/blob/439c59db962bd244ccbce21c22742d2be85f4a75/argsParser.py#L51) to set the CUDA ids according to your own computer.

**Comment by liushifu12138** [comment]
Thank you for your answer
How to train in tanks and temples?Use the DTU model directly or do I need to download tank's training set and test set?
Can you give me a link to the test set?
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/tankandtemples/intermediate/Cameras/pair.txt'

**Comment by ArthasMil** [comment]
You need to download the training set [here](https://www.tanksandtemples.org/) and submit the test results for online evaluation. And the dataloader should be changed to adapt new dataset, [this code](https://github.com/jzhangbs/Vis-MVSNet/blob/master/data/tnt_training.py) could be a reference.

**Comment by liushifu12138** [comment]
Could you share your code? please
